service: site-creation-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: ap-southeast-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendRawEmail'
      Resource:
        '*'

functions:
  sites:
    handler: dist/serverless.handler
    timeout: 30
    environment:
      FORM_CREATE_KEY: ${env:FORM_CREATE_KEY}
      NETLIFY_ACCESS_TOKEN: ${env:NETLIFY_ACCESS_TOKEN}
      NETLIFY_APP_ID: ${env:NETLIFY_APP_ID}
    events:
      - http:
          path: sites
          method: post
  users:
    handler: dist/serverless.handler
    timeout: 30
    environment:
      FORM_USERS_KEY: ${env:FORM_USERS_KEY}
    events:
      - http:
          path: users
          method: post
  live:
    handler: dist/serverless.handler
    timeout: 30
    environment:
      FORM_LIVE_KEY: ${env:FORM_LIVE_KEY}
      JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    events:
      - http:
          path: live
          method: post
  approve:
    handler: dist/serverless.handler
    timeout: 30
    environment:
      FORM_LIVE_KEY: ${env:FORM_LIVE_KEY}
      JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
      KEYCDN_ACCESS_TOKEN: ${env:KEYCDN_ACCESS_TOKEN}
      CLOUDFLARE_TOKEN: ${env:CLOUDFLARE_TOKEN}
      CLOUDFLARE_ZONE_ID: ${env:CLOUDFLARE_ZONE_ID}
      NETLIFY_ACCESS_TOKEN: ${env:NETLIFY_ACCESS_TOKEN}
      NETLIFY_APP_ID: ${env:NETLIFY_APP_ID}
    events:
      - http:
          path: approve
          method: get
