service: site-creation-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: ap-southeast-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
    NETLIFY_ACCESS_TOKEN: ${env:NETLIFY_ACCESS_TOKEN}
    NETLIFY_APP_ID: ${env:NETLIFY_APP_ID}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendRawEmail'
      Resource:
        '*'

functions:
  sites:
    handler: dist/serverless.handler
    timeout: 30
    environment:
      FORM_CREATE_KEY: ${env:FORM_CREATE_KEY}
    events:
      - http:
          path: sites
          method: post
