title: Title
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon-isomer.ico

# Site colors
colors:
  primary-color: '#6031b6'
  secondary-color: '#4372d6'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'


